### ISSUE TITLE
mongodb template TLS

### ISSUE THREAD

**Issue by johnstonmatt** [polyseam/cndi#300]
Serving the MongoDB community chart over the internet using TLS currently relies on self-signed certificates, we would prefer to not require client certificates instead relying on letsencrypt

https://github.com/mongodb/mongodb-kubernetes-operator#mongodb-community-kubernetes-operator

**Comment by johnstonmatt** [comment]
Needs TLS

**Comment by harshil4076** [comment]
There is this discussion on LetsEncrypt not creating a ca file.

https://community.letsencrypt.org/t/whats-the-ca-file-does-letsencrypt-even-create-one/26430

**Comment by harshil4076** [comment]
https://community.letsencrypt.org/t/why-doesnt-lets-encrypt-issue-ca-certificates/144386

**Comment by harshil4076** [comment]
https://github.com/cert-manager/cert-manager/issues/1571

**Comment by harshil4076** [comment]
https://cert-manager.io/docs/concepts/certificate/#:~:text=When%20configuring%20a,and%20private%20key.

**Comment by harshil4076** [comment]
## Internal TLS vs External TLS
Mongodb community operator has this Agent and ReadinessProbe which makes internal request to the mongodb-replica-set on startup. The pod will start only if this internal request from the Agent and ReadinessProbe is successful.
It is made from within the cluster using the svc url <replicasetname>.<replicasername-svc>.<namespace>.svc.cluster.local.

If we enable the tls option in crd it expects a single CA certificate issued for the internal url <replicasetname>.<replicasername-svc>.<namespace>.svc.cluster.local as well as the external url mongodb-replica-set.example.com. 

For a secured internal connection we need to issue a CA Certificate. Since letsEncrypt only issues certificates for FQDN, we can not use the letsEncrypt secret for internal connection. 

One option would be to have two Cert issuers, Internal and External. But at this point the Community Helm chart does not support that. I couldn't find any way to configure the Agent and Readiness probe to use the Selfsigned for internal communication only.


The options here are to use the SelfSigned certificate or a Custom CA provider which can issue certificates for both external and internal urls.
